//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class catAreasPerfiles
    {
        public int AreasPerfilesID { get; set; }
        public Nullable<int> PerfilID { get; set; }
        public Nullable<int> AreaID { get; set; }
    }
}
