//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ERP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catBusquedaUsuario> catBusquedaUsuario { get; set; }
        public virtual DbSet<Corporativo> Corporativo { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<catAreas> catAreas { get; set; }
        public virtual DbSet<catAreasPerfiles> catAreasPerfiles { get; set; }
        public virtual DbSet<catGeneros> catGeneros { get; set; }
        public virtual DbSet<catPerfiles> catPerfiles { get; set; }
    }
}
