//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public System.Guid UsuarioID { get; set; }
        public Nullable<int> TipoUsuarioID { get; set; }
        public Nullable<int> PerfilID { get; set; }
        public string CodigoUsuario { get; set; }
        public string Usuario { get; set; }
        public byte[] Clave { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string CorreoPersonal { get; set; }
        public string CorreoTrabajo { get; set; }
        public string Celular { get; set; }
        public Nullable<int> ubicacionID { get; set; }
        public Nullable<int> EstatusRegistroID { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public System.Guid CorporativoID { get; set; }
    }
}
